services:
  app:
    build: .
    ports: ["4000:4000"]
    env_file: .env
    depends_on:
      - db
    # volumes: ["./src:/app/src"]  # 本地调试可开

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


